# simple linear regression

In [ ]:
import pandas as pd
df=pd.read_csv("Book1.csv")
df

In [ ]:
x=df.iloc[:,0:1]
y=df.iloc[:,-1]
print(x)
print(y)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=41)
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

In [ ]:
m=lr.coef_
m

In [ ]:
c=lr.intercept_
c

In [ ]:
y_pred=lr.predict(x_test)
print(y_test)
y_pred

In [ ]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
print("mae:",mean_absolute_error(y_test,y_pred))
print("mse:",mean_squared_error(y_test,y_pred))
print("r2_score:",r2_score(y_test,y_pred))

In [ ]:
#test model with your cgpa
import numpy as np
x_t=np.array([9.4]).reshape(-1,1)
print(x_t)

In [ ]:
lr.predict(x_t)

In [ ]:
import matplotlib.pyplot as plt
plt.scatter(df["cgpa"],df["package"])
plt.plot(x_test,lr.predict(x_test))
plt.xlabel("cgpa")
plt.ylabel("package")
plt.show()

multiple linear regression

In [ ]:
import pandas as pd
df=pd.read_csv("car data.csv")
df.head()

In [ ]:
df.isna().sum()

df["age"]=2026-df["Year"]
df.info()

x=df[["Present_Price","Kms_Driven","Fuel_Type","Seller_Type","Transmission","Owner","age"]]
y=df["Selling_Price"]
x=pd.get_dummies(x,drop_first=True)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=20)

from sklearn.linear_model import LinearRegression
lr=LinearRegression()

lr.fit(x_train,y_train)

y_pred=lr.predict(x_test)

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
print("coefficients:",lr.coef_)
print("intercept:",lr.intercept_)
print("MAE:",mean_absolute_error(y_test,y_pred))
print("MSE:",mean_squared_error(y_test,y_pred))
print("r2score:",r2_score(y_test,y_pred))

In [ ]:
#task- write a python program to predict house price from "RealEstate.csv"
#dataset using linear regression algorithm.
#display MSE and R2 score of model
df=pd.read_csv("RealEstate.csv")
x=df.iloc[:,1:7]
y=df.iloc[:,-1]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.15,
                                               random_state=45)

from sklearn.linear_model import LinearRegression
lr=LinearRegression()

lr.fit(x_train,y_train)

y_pred=lr.predict(x_test)

from sklearn.metrics import mean_squared_error,r2_score
#print("coefficients:",lr.coef_)
#print("intercept:",lr.intercept_)
#print("MAE:",mean_absolute_error(y_test,y_pred))
print("MSE:",mean_squared_error(y_test,y_pred))
print("r2score:",r2_score(y_test,y_pred))

In [ ]:
#pb 228
df=pd.read_csv("WinequalityN.csv")
df

In [ ]:
df.isna().sum()

In [ ]:
df["fixed acidity"].fillna(df["fixed acidity"].mean())
df["volatile acidity"].fillna(df["volatile acidity"].mean(),inplace=True)
df["citric acid"].fillna(df["citric acid"].mean(),inplace=True)
df["fixed acidity"].fillna(df["fixed acidity"].mean(),inplace=True)
df["residual sugar"].fillna(df["residual sugar"].mean(),inplace=True)
df["chlorides"].fillna(df["chlorides"].mean(),inplace=True)
df["pH"].fillna(df["pH"].mean(),inplace=True)
df["sulphates"].fillna(df["sulphates"].mean(),inplace=True)
df.isna().sum()

In [ ]:
x=df.iloc[:,0:12]
y=df.iloc[:,-1]
x=pd.get_dummies(x)
print(x)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,
                                               random_state=20)

from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
from sklearn.metrics import mean_squared_error,r2_score
#print("coefficients:",lr.coef_)
#print("intercept:",lr.intercept_)
#print("MAE:",mean_absolute_error(y_test,y_pred))
print("MSE:",mean_squared_error(y_test,y_pred))
print("r2score:",r2_score(y_test,y_pred))
import numpy as np
x_t=np.array([8,0.4,0.40,15,0.048,40,150,0.99,3,0.45,10.5,True,False]).reshape(1,-1)
pred=lr.predict(x_t)
pred

In [ ]:
# polynomial regression

In [ ]:
import pandas as pd
df=pd.DataFrame({"temp":[0,20,40,60,80,100],"pressure":[0.0002,0.0012,0.0060,0.03,
                                                        0.09,0.27]})
df

In [ ]:
x=df[["temp"]]
y=df["pressure"]

from sklearn.preprocessing import PolynomialFeatures

poly=PolynomialFeatures(degree=3)
poly_x=poly.fit_transform(x)

from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(poly_x,y)

pred1=lr.predict(poly_x)
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error

print("MAE:",mean_absolute_error(y,pred1))
print("MSE:",mean_squared_error(y,pred1))
print("r2score:",r2_score(y,pred1))

#simple linear regression
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x,y)

pred2=lr.predict(x)
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error

print("MAE:",mean_absolute_error(y,pred2))
print("MSE:",mean_squared_error(y,pred2))
print("r2score:",r2_score(y,pred2))

import matplotlib.pyplot as plt
plt.scatter(df["temp"],y)
plt.plot(df["temp"],pred2)
plt.plot(df["temp"],pred1)

In [ ]:
df=pd.read_csv("Ice_cream selling data.csv")
df.head()

In [ ]:
x=df.iloc[:,0:1]
y=df.iloc[:,-1]

from sklearn.preprocessing import PolynomialFeatures

poly=PolynomialFeatures(degree=4)
poly_x=poly.fit_transform(x)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(poly_x,y,test_size=0.15,random_state=25)
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

pred1=lr.predict(x_test)
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error

print("MAE:",mean_absolute_error(y_test,pred1))
print("MSE:",mean_squared_error(y_test,pred1))
print("r2score:",r2_score(y_test,pred1))

import matplotlib.pyplot as plt
plt.scatter(df["Temperature (°C)"],y)
plt.plot(df["Temperature (°C)"],lr.predict(poly_x))
plt.show()
#plt.plot(df["temp"],pred1)

In [ ]:
#classification

In [23]:
#k nearest neighbors
import pandas as pd
df=pd.read_csv("diabetes.csv")
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [24]:
x=df.iloc[:,0:8]
y=df.iloc[:,-1]

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.15,random_state=25)

from sklearn.neighbors import KNeighborsClassifier
kn=KNeighborsClassifier(n_neighbors=27)

model=kn.fit(x_train,y_train)
y_pred=model.predict(x_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)
print("TN:",cm[0][0])
print("TP:",cm[1][1])
print("FN:",cm[1][0])
print("FP:",cm[0][1])
#find accuracy,error rate , specificity and sensitivity
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

#print("cm:",confusion_matrix(y_test,y_pred))
print("acc:",accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[68  8]
 [24 16]]
TN: 68
TP: 16
FN: 24
FP: 8
acc: 0.7241379310344828
              precision    recall  f1-score   support

           0       0.74      0.89      0.81        76
           1       0.67      0.40      0.50        40

    accuracy                           0.72       116
   macro avg       0.70      0.65      0.65       116
weighted avg       0.71      0.72      0.70       116

# Decision tree classification

In [ ]:
import pandas as pd
df=pd.read_csv("DecisionTreeDataset -Num.csv")
print(df)
x=df.iloc[:,0:4]
y=df.iloc[:,-1]
from sklearn.tree import DecisionTreeClassifier,plot_tree
d_tree=DecisionTreeClassifier(criterion="entropy",max_depth=5)
d_tree.fit(x,y)

print(d_tree.get_depth())

from sklearn import tree
print("text representation of D_tree:",tree.export_text(d_tree))

print("graphical representation")
plot_tree(d_tree,filled=True)

y_pred=d_tree.predict(x)

from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

print("cm:",confusion_matrix(y,y_pred))
print("acc:",accuracy_score(y,y_pred))
print(classification_report(y,y_pred))

In [8]:
# decision tree
import pandas as pd
df=pd.read_csv("diabetes.csv")
df.head()
x=df.iloc[:,0:8]
y=df.iloc[:,-1]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.15,random_state=25)
from sklearn.tree import DecisionTreeClassifier,plot_tree
d_tree=DecisionTreeClassifier(criterion="entropy",max_depth=5)
d_tree.fit(x_train,y_train)
print(d_tree.get_depth())
from sklearn import tree
#print("text representation of D_tree:",tree.export_text(d_tree))
#print("graphical representation")
#plot_tree(d_tree,filled=True)
y_pred=d_tree.predict(x_test)
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print("cm:",confusion_matrix(y_test,y_pred))
print("acc:",accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))


# create KNN and DT model and compare accuracy score of both for this dataset
df=pd.read_csv("data_breast_cancer.csv")
x=df.iloc[:,2:32]
y=df.iloc[:,1]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
from sklearn.tree import DecisionTreeClassifier,plot_tree
d_tree=DecisionTreeClassifier(criterion="entropy",max_depth=16)
d_tree.fit(x_train,y_train)
print(d_tree.get_depth())
from sklearn import tree
#print("text representation of D_tree:",tree.export_text(d_tree))
#print("graphical representation")
#plot_tree(d_tree,filled=True)
y_pred=d_tree.predict(x_test)
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print("cm:",confusion_matrix(y_test,y_pred))
print("acc:",accuracy_score(y_test,y_pred))

5
cm: [[63 13]
 [13 27]]
acc: 0.7758620689655172
              precision    recall  f1-score   support

           0       0.83      0.83      0.83        76
           1       0.68      0.68      0.68        40

    accuracy                           0.78       116
   macro avg       0.75      0.75      0.75       116
weighted avg       0.78      0.78      0.78       116

7
cm: [[70  1]
 [ 5 38]]
acc: 0.9473684210526315

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
kn=KNeighborsClassifier(n_neighbors=23)

model=kn.fit(x_train,y_train)
y_pred=model.predict(x_test)
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print("cm:",confusion_matrix(y_test,y_pred))
print("acc:",accuracy_score(y_test,y_pred))

In [ ]:
# create KNN and DT model and compare accuracy score of both for  dataset iris.csv

In [ ]:
# create KNN and DT model and compare accuracy score of both for  dataset night_out.csv
#(dont split dataset in training and testing) 
#predict the Night_out knn and DT model for below input data
# GF_Mood=Good, Money=Medium, Assignment_Work=Yes

In [8]:
import pandas as pd
import numpy as np
df=pd.read_csv("night_out.csv")
df

   GF_Mood   Money Assignment_Work Night_Out
0     Good    High              No       Yes
1     Good  Medium              No       Yes
2     Good     Low              No        No
3     Good    High             Yes       Yes
4     Good  Medium             Yes        No
5      Bad    High              No       Yes
6      Bad  Medium              No        No
7      Bad     Low              No        No
8      Bad    High             Yes        No
9      Bad  Medium             Yes        No
10     Bad     Low             Yes        No
11    Good     Low             Yes        No
12    Good    High              No       Yes
13     Bad    High              No       Yes
14    Good  Medium              No       Yes

In [9]:
x=df.iloc[:,0:-1]
x=pd.get_dummies(x,drop_first=True)
print(x)
y=df.iloc[:,-1]
from sklearn.tree import DecisionTreeClassifier,plot_tree
d_tree=DecisionTreeClassifier(criterion="entropy",max_depth=5)
d_tree.fit(x,y)
y_pred=d_tree.predict(x)
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print("cm:",confusion_matrix(y,y_pred))
print("acc:",accuracy_score(y,y_pred))
print("prediction for DT:",d_tree.predict(np.array([True,False,True,True]).reshape(1,-1)))

from sklearn.neighbors import KNeighborsClassifier
kn=KNeighborsClassifier(n_neighbors=3)
model=kn.fit(x,y)
y_pred=model.predict(x)
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print("cm:",confusion_matrix(y,y_pred))
print("acc:",accuracy_score(y,y_pred))
print("prediction for knn:",kn.predict(np.array([True,False,True,True]).reshape(1,-1)))

    GF_Mood_Good  Money_Low  Money_Medium  Assignment_Work_Yes
0           True      False         False                False
1           True      False          True                False
2           True       True         False                False
3           True      False         False                 True
4           True      False          True                 True
5          False      False         False                False
6          False      False          True                False
7          False       True         False                False
8          False      False         False                 True
9          False      False          True                 True
10         False       True         False                 True
11          True       True         False                 True
12          True      False         False                False
13         False      False         False                False
14          True      False          True                False
cm: [[8 0]
 [0 7]]
acc: 1.0
prediction for DT: ['No']
cm: [[5 3]
 [0 7]]
acc: 0.8
prediction for knn: ['Yes']

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

# Random Forest Classifier

In [21]:
import pandas as pd
df=pd.read_csv("diabetes.csv")
df.head()
x=df.iloc[:,0:8]
y=df.iloc[:,-1]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.15,random_state=25)
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=100,random_state=42,max_depth=5) 
#n_estimators number of decision trees in forest
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
print("cm: \n",confusion_matrix(y_test,y_pred))
print("acc: ",accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

cm:
 [[69  7]
 [17 23]]
acc:  0.7931034482758621
              precision    recall  f1-score   support

           0       0.80      0.91      0.85        76
           1       0.77      0.57      0.66        40

    accuracy                           0.79       116
   macro avg       0.78      0.74      0.75       116
weighted avg       0.79      0.79      0.78       116

In [ ]:
#create knn,decision tree and random forest classification model for glass.csv 
#comare accuracy of them
# split dataset in training and testing with
#test_size=0.2,random_state=42,n_neighbors=15,max_depth=,n_estimators=100

In [29]:
#pb q-230

df=pd.read_csv("windpower.csv")
df=df.dropna()
df.info()
x=df.iloc[:,0:1]
y=df.iloc[:,-1]
for i in range(3,7):
    from sklearn.preprocessing import PolynomialFeatures
    poly=PolynomialFeatures(degree=i)
    poly_x=poly.fit_transform(x)
    from sklearn.model_selection import train_test_split
    x_train,x_test,y_train,y_test=train_test_split(poly_x,y,test_size=0.25,
                                                   random_state=42)
    from sklearn.linear_model import LinearRegression
    lr=LinearRegression()
    lr.fit(x_train,y_train)
    pred1=lr.predict(x_test)
    from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error
    print("MSE:",mean_squared_error(y_test,pred1))
    print("r2score:",r2_score(y_test,pred1))

<class 'pandas.core.frame.DataFrame'>
Index: 492 entries, 0 to 499
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Power (kW)        492 non-null    float64
 1   Wind speed (m/s)  492 non-null    float64
dtypes: float64(2)
memory usage: 11.5 KB
MSE: 20.66556538623966
r2score: 0.6610870594227045
MSE: 20.56252720857651
r2score: 0.662776873910277
MSE: 19.400268788881124
r2score: 0.6818377808522166
MSE: 18.915428320751914
r2score: 0.6897891098235476

In [5]:
import pandas as pd
df=pd.read_csv("diabetes.csv")
df.head()
x=df.iloc[:,0:8]
y=df.iloc[:,-1]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
from sklearn.svm import SVC
s=SVC(kernel="rbf",random_state=42,gamma="scale",C=10) 
#C= regulaization parameter high C= high -->more margin& less error
#C=low-->small margin & more error
# gamma-- controls influence of points(for rbf)---high gamma-overfitting,
#low gamma- underfitting
# kernal tranforms data into higher dimension to make it seperable
# kernal= types of kernal (linear, rbf,poly) 
#rbf-most powerfull and commonly used in classification
s.fit(x_train,y_train)
y_pred=s.predict(x_test)
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
print("cm: \n",confusion_matrix(y_test,y_pred))
print("acc: ",accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

cm:
 [[87 12]
 [24 31]]
acc:  0.7662337662337663
              precision    recall  f1-score   support

           0       0.78      0.88      0.83        99
           1       0.72      0.56      0.63        55

    accuracy                           0.77       154
   macro avg       0.75      0.72      0.73       154
weighted avg       0.76      0.77      0.76       154

In [ ]:
df=pd.read_csv("data_breast_cancer.csv")
x=df.iloc[:,2:32]
y=df.iloc[:,1]

In [5]:
# 9 marks practice 

import pandas as pd
df=pd.read_csv("Employee_attrition.csv")
df=df.drop("Employee_ID",axis=1)
x=df.drop("Attrition",axis=1)
y=df["Attrition"]
x=pd.get_dummies(x,drop_first=True)
print(x)

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,accuracy_score
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
acc_list=[]
for k in range(1,26):
    knn=KNeighborsClassifier(n_neighbors=k)
    knn.fit(x_train,y_train)
    y_pred=knn.predict(x_test)
    acc=accuracy_score(y_test,y_pred)
    acc_list.append(acc)
    print(f"k={k},accuracy={acc}")
    
m=max(acc_list)
best_k=acc_list.index(m)+1
print("best_k=",best_k)

knn_final=KNeighborsClassifier(n_neighbors=best_k)
knn_final.fit(x_train,y_train)
#random forest
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(criterion="entropy",n_estimators=150,random_state=42)
rf.fit(x_train,y_train)

y_pred1=rf.predict(x_test)
print("for random forest")
print("cm=",confusion_matrix(y_test,y_pred1))
print("accuracy",accuracy_score(y_test,y_pred1))
# prediction for new data
import numpy as np

x_t=np.array([30,45000,5,3,10,True,False,False,True,False,True,False,False]).reshape(1,-1)
print("prediction for knn=",knn_final.predict(x_t))
print("prediction for rf=",rf.predict(x_t))

     Age  Monthly_Income  Years_at_Company  Job_Satisfaction  \
0     29           23278                 8                 1
1     56           31395                18                 1
2     54           98907                 0                 2
3     39           20851                 5                 2
4     28           32156                12                 3
..   ...             ...               ...               ...
245   46           39369                 7                 2
246   42           74890                 4                 4
247   52          116447                 1                 3
248   55           69391                10                 3
249   38           99963                15                 3

     Distance_From_Home  Job_Role_Developer  Job_Role_HR  Job_Role_Manager  \
0                    22               False        False              True
1                     7               False         True             False
2                    15               False        False              True
3                     7               False         True             False
4                    26                True        False             False
..                  ...                 ...          ...               ...
245                   1                True        False             False
246                  17               False         True             False
247                  22               False        False              True
248                  22               False        False              True
249                   8               False        False              True

     Work_Life_Balance_Good  Work_Life_Balance_Poor  Overtime_Yes  \
0                     False                    True          True
1                     False                    True          True
2                     False                   False         False
3                      True                   False         False
4                      True                   False         False
..                      ...                     ...           ...
245                   False                   False          True
246                   False                   False          True
247                   False                   False          True
248                    True                   False         False
249                   False                    True         False

     Education_Postgraduate  Education_School
0                      True             False
1                     False              True
2                      True             False
3                     False             False
4                     False              True
..                      ...               ...
245                   False             False
246                    True             False
247                   False             False
248                    True             False
249                   False             False

[250 rows x 13 columns]
k=1,accuracy=0.86
k=2,accuracy=0.94
k=3,accuracy=0.94
k=4,accuracy=0.94
k=5,accuracy=0.94
k=6,accuracy=0.94
k=7,accuracy=0.94
k=8,accuracy=0.94
k=9,accuracy=0.94
k=10,accuracy=0.94
k=11,accuracy=0.94
k=12,accuracy=0.94
k=13,accuracy=0.94
k=14,accuracy=0.94
k=15,accuracy=0.94
k=16,accuracy=0.94
k=17,accuracy=0.94
k=18,accuracy=0.94
k=19,accuracy=0.94
k=20,accuracy=0.94
k=21,accuracy=0.94
k=22,accuracy=0.94
k=23,accuracy=0.94
k=24,accuracy=0.94
k=25,accuracy=0.94
best_k= 2
for random forest
cm= [[47  0]
 [ 1  2]]
accuracy 0.98
prediction for knn= [0]
prediction for rf= [0]

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [ ]:
#write a python program to predict booking_status using
#random forest and svc for "Hotel Reservation.csv"
# load dataset, drop bookingt_ID column, convert categorical to numeric
#split data in to train and test(80%-20%),random_state=42
#random forest: 
#train random forest model for values of n_estimators from 61 to 70,criterion="entropy"
#random_state=42
#find the best n_estimators based on highest accuracy
#train the final random forest model using best 

#svc:
#train svc model using C=10,random_state=42,kernel="rbf"
#find accuracy and confusion matrix

In [6]:
import pandas as pd
df=pd.read_csv("Hotel Reservations.csv")
print(df.info())
df=df.drop("Booking_ID",axis=1)
x=df.drop("booking_status",axis=1)
y=df["booking_status"]
x=pd.get_dummies(x,drop_first=True)
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix,accuracy_score
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
acc_list=[]
for e in range(61,71):
    rf=RandomForestClassifier(n_estimators=e,random_state=42,criterion="entropy")
    rf.fit(x_train,y_train)
    y_pred=rf.predict(x_test)
    acc=accuracy_score(y_test,y_pred)
    acc_list.append(acc)
    print(f"e={e},accuracy={acc}")  
m=max(acc_list)
best_e=acc_list.index(m)+61
print("best_e=",best_e)
rf_final=RandomForestClassifier(n_estimators=best_e,criterion="entropy",random_state=42)
rf_final.fit(x_train,y_train)
y_pred1=rf_final.predict(x_test)
print("for random forest")
print("cm=",confusion_matrix(y_test,y_pred1))
print("accuracy",accuracy_score(y_test,y_pred1))
#svc
from sklearn.svm import SVC
s=SVC(C=40,random_state=42,kernel="rbf")
s.fit(x_train,y_train)
y_pred1=s.predict(x_test)
print("for svc")
print("cm=",confusion_matrix(y_test,y_pred1))
print("accuracy",accuracy_score(y_test,y_pred1))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36275 entries, 0 to 36274
Data columns (total 19 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Booking_ID                            36275 non-null  object
 1   no_of_adults                          36275 non-null  int64
 2   no_of_children                        36275 non-null  int64
 3   no_of_weekend_nights                  36275 non-null  int64
 4   no_of_week_nights                     36275 non-null  int64
 5   type_of_meal_plan                     36275 non-null  object
 6   required_car_parking_space            36275 non-null  int64
 7   room_type_reserved                    36275 non-null  object
 8   lead_time                             36275 non-null  int64
 9   arrival_year                          36275 non-null  int64
 10  arrival_month                         36275 non-null  int64
 11  arrival_date                          36275 non-null  int64
 12  market_segment_type                   36275 non-null  object
 13  repeated_guest                        36275 non-null  int64
 14  no_of_previous_cancellations          36275 non-null  int64
 15  no_of_previous_bookings_not_canceled  36275 non-null  int64
 16  avg_price_per_room                    36275 non-null  float64
 17  no_of_special_requests                36275 non-null  int64
 18  booking_status                        36275 non-null  object
dtypes: float64(1), int64(13), object(5)
memory usage: 5.3+ MB
None
e=61,accuracy=0.9037904893177119
e=62,accuracy=0.9035148173673329
e=63,accuracy=0.9047553411440385
e=64,accuracy=0.9046175051688491
e=65,accuracy=0.9046175051688491
e=66,accuracy=0.9047553411440385
e=67,accuracy=0.9048931771192281
e=68,accuracy=0.9053066850447967
e=69,accuracy=0.9050310130944177
e=70,accuracy=0.9050310130944177
best_e= 68
for random forest
cm= [[1995  421]
 [ 266 4573]]
accuracy 0.9053066850447967
for svc
cm= [[ 815 1601]
 [ 182 4657]]
accuracy 0.7542384562370779